### ISSUE TITLE
Cannot delete lists

### ISSUE THREAD

**Issue by Catstik** [MegaSa1nt/GMDprivateServer#17]

**Comment by MegaSa1nt** [comment]
any additional info? are you sure you applied all files and SQL correctly? check it through this list: https://github.com/Cvolton/GMDprivateServer/pull/1043/files

**Comment by Catstik** [comment]
Pretty sure, also with lists gd has something with how many levels you complete in that list, which also I dont think is here either

**Comment by Catstik** [comment]
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/91972350/0a8a0ccd-dddd-4b5c-ab35-37fa74e2e1d2)

> any additional info? are you sure you applied all files and SQL correctly? check it through this list: https://github.com/Cvolton/GMDprivateServer/pull/1043/files
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/91972350/c2f21c1d-3232-4f9d-b416-aac5265e84f1)

**Comment by MegaSa1nt** [comment]
what happens when you try to comment `!d` or `!delete` on a list?

**Comment by MegaSa1nt** [comment]
> Pretty sure, also with lists in main gd has something with how many levels required to complete the list, which also I dont think is here either

can you tell what list is this to check it?

**Comment by Catstik** [comment]
> what happens when you try to comment `!d` or `!delete` on a list?

That works

**Comment by Catstik** [comment]
> > Pretty sure, also with lists in main gd has something with how many levels required to complete the list, which also I dont think is here either
> 
> can you tell what list is this to check it?

Pretty much any list but an example could be id -24719

**Comment by MegaSa1nt** [comment]
> That works

You're talking about delete button? I forgot about it, thanks, will do a bit later, sorry lol

**Comment by Catstik** [comment]
> > That works
> 
> You're talking about delete button? I forgot about it, thanks, will do a bit later, sorry lol

it's fine lol

**Comment by Catstik** [comment]
And what about the required amount of levels to beat in a list

**Comment by MegaSa1nt** [comment]
> And what about the required amount of levels to beat in a list

Cant check rn

**Comment by Catstik** [comment]
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/91972350/5f5cc61a-e326-427b-8e07-b33813f47cb6)
heres the level id that i gave you

**Comment by MegaSa1nt** [comment]
Done, pls check

**Comment by Catstik** [comment]
Works but still cant delete lists with delete button

**Comment by MegaSa1nt** [comment]
are you sure you put both `deleteGJLevelList.php`?

**Comment by Catstik** [comment]
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/91972350/639dc0b4-fbdc-415e-9a1a-675169288ca3)
Yeah and I still get it (ignore top level)

**Comment by MegaSa1nt** [comment]
can you send your gdps link?

**Comment by Catstik** [comment]
https://ps.fhgdps.com/ccatstikgdps

**Comment by MegaSa1nt** [comment]
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/49565695/f1bede7f-7f93-4e71-983f-d51928f57dd8)

**Comment by Catstik** [comment]
oh yeah i forgot that one oopsies

**Comment by Catstik** [comment]
🧠

**Comment by MegaSa1nt** [comment]
dw

**Comment by Catstik** [comment]
yeah it works now

**Comment by MegaSa1nt** [comment]
nice

**Comment by Catstik** [comment]
I think it's all done now

**Comment by Catstik** [comment]
Saving level lists doesnt work im pretty sure though, although that was like 3-4 hours ago

**Comment by Catstik** [comment]
just checked, they dont

**Comment by MegaSa1nt** [comment]
wdym "Saving level lists"?
